name: words_and_hammers
description: "A fast, fluid and immersive competitive word puzzle experience..."
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.13.1
  collection: ^1.19.1
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    # Özel Dosyalar
    - .env
    # Oyun Bölümleri
    - assets/
    - assets/images/
    - assets/images/logos/
    - assets/stages/
    - assets/stages/tr/
    - assets/stages/en/